name: mundial
version: "1.0.0"
config-version: 2

profile: mundial

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  mundial:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
